name: Publish release of new version manually

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Name of release  (ie bug fixes)'
        required: true
      tag_name:
        description: 'Name of tag  (ie testing)'
        required: true

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout changes
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Get release version
        run: echo "version=$(./gradlew properties -q | grep 'version:' | awk '{print $2}')" >> $GITHUB_ENV

      - name: Print product version
        run: echo $version

      - name: Upload jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: 'allure-notifications-${{env.version}}.jar'
          path: build/libs/*.jar

      - name: Create Changelog
        id: changelog
        uses: scottbrenner/generate-changelog-action@master
        env:
          REPO: ${{ github.repository }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_name }}
          body:  ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Attach jar to release
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/allure-notifications-${{env.version}}.jar
          asset_name: 'allure-notifications-${{env.version}}.jar'
          asset_content_type: application/java-archive

      - name: Publish Release
        uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}

      - name: Send notification via telegram/slack
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: |
            *allure-notifications-${{env.version}} is now available for downloading at the link* https://github.com/${{ github.repository }}/releases/latest/download/allure-notifications-${{env.version}}.jar
            *See Changelog here*:
            https://github.com/${{ github.repository }}/releases/latest/
          format: markdown
